### ISSUE TITLE
Version 

### ISSUE THREAD

**Issue by nazib** [cvlab-stonybrook/SelfMedMAE#2]
Hi

could you please mention the version of the libraries you used with complete instruction of data preprocessing and etc. I am getting lot of errors like "No module named 'timm.models.layers.helpers'". Installed timm but still getting errors. Please make a requirements.txt/yml 

regards
Nazib

**Comment by knightron0** [comment]
I used `tim==0.6.13` which seems to work. `timm.models.layers` [was moved to](https://pypi.org/project/timm/) `timm.layers` for versions `>= 0.9` which invalidates some imports.
