### ISSUE TITLE
There doesn't has BTCV\transunet.json

### ISSUE THREAD

**Issue by jinlinma** [cvlab-stonybrook/SelfMedMAE#3]
I run with BTCV, but there is a  error,

ValueError: Data list file data\BTCV\transunet.json does not exist.

What can I do? Where can download the transunet.json.

**Comment by Nioolek** [comment]
I think you should prepare a json with example:
```
        [
            {'image': '/workspace/data/chest_19.nii.gz',  'label': 0},
            {'image': '/workspace/data/chest_31.nii.gz',  'label': 1}
        ]
```

you can read the doc from 
https://github.com/Project-MONAI/MONAI/blob/dev/monai/data/decathlon_datalist.py#L115

**Comment by BannyStone** [comment]
Here is the JSON file: https://github.com/cvlab-stonybrook/TokenSparse-for-MedSeg/blob/main/lib/data/transunet.json
Will upload this file to this repo soon.
