### ISSUE TITLE
library versions

### ISSUE THREAD

**Issue by yuankaiWang** [cvlab-stonybrook/SelfMedMAE#4]
could anyone who share their version of library in this project.  Much appraciate

**Comment by BannyStone** [comment]
Thanks @jackhu-bme !
I just updated the info in README. Here are the package versions I used:
pytorch=1.7.1=py3.8_cuda10.1.243_cudnn7.6.3_0
torchvision=0.8.2=py38_cu101
monai-weekly==0.9.dev2152
nibabel==3.2.1
omegaconf==2.1.1
timm==0.4.12
